---
authors:
  - Eric Ames (ericcames)
dependencies:
  "amazon.aws": ">=7.2.0"
  "servicenow.itsm": ">=2.4.0"
license_file: LICENSE
name: redhat_automated_patching
description: Use Ansible, Insights and Servicenow to demo automated patching.
             Help your control owners demostrate continuous compliance to your auditors.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/redhat.automated.patching
issues: https://github.com/ericcames/redhat.automated.patching/issues
tags:
  - lab
  - automation
  - ansible
  - cloud
  - aws
  - amazon
  - linux
  - satellite
  - dailydemo
  - sales
  - insights
version: 0.0.0