---
- name: Clone the software repository
  delegate_to: 127.0.0.1
  register: clone_result
  run_once: true
  when: software_repository is defined
  ansible.builtin.git:
    repo: "{{ software_repository }}"
    dest: "{{ local_repo }}"
    accept_hostkey: true
    force: true

- name: Remove all playbooks that match CTASK*.yml
  delegate_to: localhost
  changed_when: false
  run_once: true
  args:
    chdir: "{{ local_repo }}"
  ansible.builtin.shell: "git rm CTASK*.yml"

- name: Get the status of the repository
  register: status_results
  changed_when: false
  ignore_errors: true
  delegate_to: localhost
  run_once: true
  args:
    chdir: "{{ local_repo }}"
  ansible.builtin.shell: "git status"

- name: Commit the changes
  when: status_results.stdout is search('Changes')
  delegate_to: localhost
  run_once: true
  environment:
    GIT_COMMITTER_NAME: "{{ git_name | default(omit) }}"
    GIT_COMMITTER_EMAIL: "{{ git_email | default(omit) }}"
    GIT_AUTHOR_NAME: "{{ git_name | default(omit) }}"
    GIT_AUTHOR_EMAIL: "{{ git_email | default(omit) }}"
  args:
    chdir: "{{ local_repo }}"
  ansible.builtin.shell: "git commit -am 'Changed'"

- name: Push the changes
  delegate_to: localhost
  run_once: true
  when: software_repository is defined
  args:
    chdir: "{{ local_repo }}"
  ansible.builtin.shell: "git push"