---
- name: Print out server_name get_insights_inventory_id
  ansible.builtin.debug:
    var: server_name

- name: Get my list
  register: my_host_list
  ignore_errors: true
  until: my_host_list.json.count > 0
  retries: 40
  delay: 10
  ansible.builtin.uri:
    url: https://console.redhat.com/api/inventory/v1/hosts?display_name={{ server_name }}
    method: GET
    user: "{{ scm_username }}"
    password: "{{ scm_password }}"
    validate_certs: false
    force_basic_auth: true
    status_code: 200
    return_content: true
    headers:
      Content-Type: application/json

- name: Print out my_insights_ids
  ansible.builtin.debug:
    msg: "{{ my_host_list.json.results[0].insights_id }}"

- name: Capture Red Hat Insights inventory id
  register: my_insights_inventory_id
  ansible.builtin.set_stats:
    data:
      my_insights_inventory_id: "{{ my_host_list.json.results[0].insights_id }}"
