---
- name: Kick off automated patching demo
  hosts: localhost
  connection: local

  tasks:

    - name: Include the get_insights_inventory_id role
      ansible.builtin.include_role:
        name: get_insights_inventory_id

    - name: Include the update_change_ticket_worknotes role
      ansible.builtin.include_role:
        name: update_change_ticket_worknotes

    - name: Include the process_cves role
      ansible.builtin.include_role:
        name: process_cves
