---
- name: Get my server name
  hosts: rheldemo
  connection: local

  tasks:

    - name: Print hostname
      ansible.builtin.debug:
        var: inventory_hostname

    # - name: Set hostname for next play
    #   register: server_name
    #   ansible.builtin.set_stats:
    #     data:
    #       server_name: "{{ inventory_hostname }}"

    - name: Set hostname for next play
      register: server_name
      ansible.builtin.set_fact:
        server_name: "{{ inventory_hostname }}"

- name: Kick off automated patching demo
  hosts: localhost
  connection: local

  tasks:

    - name: Include the get_insights_inventory_id role
      ansible.builtin.include_role:
        name: get_insights_inventory_id

    - name: Include the update_change_ticket_worknotes role
      ansible.builtin.include_role:
        name: update_change_ticket_worknotes

    - name: Include the process_cves role
      ansible.builtin.include_role:
        name: process_cves
