---
- name: Get my server name
  hosts: ec2-3-101-38-231.us-west-1.compute.amazonaws.com
  connection: local

  tasks:

    - name: Print hostname
      ansible.builtin.debug:
        var: inventory_hostname

    - name: Set hostname for next play
      ansible.builtin.set_stats:
        data:
          server_name: "{{ inventory_hostname }}"
