---
- name: Getting the insights id
  hosts: localhost
  connection: local

  tasks:

    - name: Include the get_insights_inventory_id role
      ansible.builtin.include_role:
        name: get_insights_inventory_id
